version: '2'
services:
    censorshipdetector-app:
        image: censorshipdetector
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://censorshipdetector-mysql:3306/censorshipdetector?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://censorshipdetector-elasticsearch:9200
        ports:
            - 8080:8080
    censorshipdetector-mysql:
        extends:
            file: mysql.yml
            service: censorshipdetector-mysql
    censorshipdetector-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: censorshipdetector-elasticsearch
